services:
    pgsql:
        image: 'postgres:15'
        ports:
            - '${FORWARD_DB_PORT:-5432}:5432'
        environment:
            PGPASSWORD: '${DB_PASSWORD:-secret}'
            POSTGRES_DB: '${DB_DATABASE}'
            POSTGRES_USER: '${DB_USERNAME}'
            POSTGRES_PASSWORD: '${DB_PASSWORD:-secret}'
        volumes:
            - 'dbms-practice-pgsql:/var/lib/postgresql/data'
            - './demo-big-20170815.sql:/docker-entrypoint-initdb.d/00-create-testing-database.sql'
        networks:
            - dbms-practice
        healthcheck:
            test:
                - CMD
                - pg_isready
                - '-q'
                - '-d'
                - '${DB_DATABASE}'
                - '-U'
                - '${DB_USERNAME}'
            retries: 3
            timeout: 5s
    pgadmin:
        image: dpage/pgadmin4:8.7
        environment:
            PGADMIN_DEFAULT_EMAIL: "admin@example.com"
            PGADMIN_DEFAULT_PASSWORD: "secret"
            PGADMIN_CONFIG_SERVER_MODE: "False"
        volumes:
          - dbms-practice-pgadmin-data:/var/lib/pgadmin
        networks:
          - dbms-practice
        ports:
          - "5050:80"
        restart: unless-stopped
        deploy:
          resources:
            limits:
              cpus: '0.5'
              memory: 1G

networks:
    dbms-practice:
        driver: bridge
volumes:
    dbms-practice-pgsql:
        driver: local
    dbms-practice-pgadmin-data:
        driver: local
